config/routes.rb
Rails32bootstrap::Application.routes.draw do

  devise_for :admins

  root :to => 'home#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/common/_admin_menu.html.erb
<!--
Used for https://github.com/rubykurs/bootstrap
branch auth

@Gemfile
gem 'devise'
$ rails g devise:install
$ rails g devise admin
$ rake db:migrate
-->

<ul class="nav secondary-nav">
  <% if admin_signed_in? %>
    <li><%= link_to "Sign out", destroy_admin_session_path, :method => :delete %> </li>
  <% else %>
    <li><%= link_to "Admin", new_admin_session_path %></li>
  <% end %>
</ul>

app/views/common/_flashes.html.erb
<% unless flash[:notice].blank? %>
  <div class="alert-message success">
    <%= content_tag :div, flash[:notice] %>
  </div>
<% end %>

<% unless flash[:error].blank? %>
  <div class="alert-message error">
    <%= content_tag :div, flash[:error] %>
  </div>
<% end %>

<% unless flash[:alert].blank? %>
  <div class="alert-message warning">
    <%= content_tag :div, flash[:alert] %>
  </div>
<% end %>

app/views/home/index.html.erb
<!-- Main hero unit for a primary marketing message or call to action -->
<div class="hero-unit">
  <h1>Hello, world!</h1>
  <p>Vestibulum id ligula porta felis euismod semper. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.</p>
  <p><a class="btn primary large">Learn more &raquo;</a></p>

</div>

<!-- Example row of columns -->
<div class="row">
  <div class="span6">
    <h2>Heading</h2>
    <p>Etiam porta sem malesuada magna mollis euismod. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.</p>
    <p><a class="btn" href="#">View details &raquo;</a></p>

  </div>
  <div class="span5">
    <h2>Heading</h2>
     <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
    <p><a class="btn" href="#">View details &raquo;</a></p>
 </div>
  <div class="span5">

    <h2>Heading</h2>
    <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
    <p><a class="btn" href="#">View details &raquo;</a></p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails32bootstrap</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="topbar">
    <div class="fill">
      <div class="container">
        <a class="brand" href="#">Project name</a>

        <ul class="nav">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#contact">Contact</a></li>
        </ul>
        <%= render :partial => 'common/admin_menu' %>
      </div>
    </div>

  </div>
  <div class="container">
  <%= render :partial => 'common/flashes' %>
    <%= yield %>
    <footer>
      <p>&copy; Company 2011</p>

    </footer>
  </div><!-- /container -->

</body>
</html>